version: "3.7"

services:
    express:
        build:
            context: ./api/
            dockerfile: ./Dockerfile
        env_file:
            - ./api/.env
        ports:
            - 8080:8080
        restart: always
        command: [node, 'server.js']
    angular_nginx:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - express
        ports:
           - 443:443
           - 80:80
        restart: always
        command: [nginx, '-g', 'daemon off;']
