version: "3.3"

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
           - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
           - 80:80
        command: [nginx, '-g', 'daemon off;']
