version: "3.3"

services:
    express:
        build:
            context: ./api/
            dockerfile: ./Dockerfile
        env_file:
            - ./api/.env
        ports:
            - 8080:8080
        command: [node, 'server.js']
    angular_nginx:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
           - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
           - 80:80
        command: [nginx, '-g', 'daemon off;']
